# Copyright © Advanced Micro Devices, Inc., or its affiliates.
#
# SPDX-License-Identifier: MIT
# Touch to trigger CI to rebuild and republish the EPYC base image.

base_image:
  base_registry_namespace: amdih
  base_repository: zendnn_zentorch
  base_tag: vllm_v0.18.0_zentorch_v5.2.1_ubuntu22.04_r5.2.1
  registry_host: docker.io
