# Copyright © Advanced Micro Devices, Inc., or its affiliates.
#
# SPDX-License-Identifier: MIT
# Touch to trigger CI to rebuild and republish the EPYC base image.

base_image:
  base_registry_namespace: amdih
  base_repository: zentorch_vllm_upstream
  base_tag: v0.22.1_ubuntu22.04
  registry_host: docker.io
