# Copyright © Advanced Micro Devices, Inc., or its affiliates.
#
# SPDX-License-Identifier: MIT

base_image:
  base_registry_namespace: amdih
  base_repository: zendnn_zentorch
  base_tag: vllm_v0.13.0_zentorch_v5.2.0_ubuntu22.04_2026_ww02
  registry_host: docker.io
