# Copyright © Advanced Micro Devices, Inc., or its affiliates.
#
# SPDX-License-Identifier: MIT

base_image:
  base_registry_namespace: vllm
  base_repository: vllm-openai-rocm
  base_tag: "v0.19.1"
  registry_host: docker.io
