# Copyright © Advanced Micro Devices, Inc., or its affiliates.
#
# SPDX-License-Identifier: MIT

apiVersion: aim.eai.amd.com/v1alpha1
kind: AIMClusterModelSource
metadata:
  name: {{ release.metadata_name }}
spec:
  filters:
{% for image in release.images %}
  {% if image.is_base %}
    # - image: {{ release.namespace }}/{{ image.repository }}:{{ image.tag }}
  {% else %}
    - image: {{ release.namespace }}/{{ image.repository }}:{{ image.tag }}
  {% endif %}
{% endfor %}
{% if release.image_pull_secret %}
  imagePullSecrets:
    - name: {{ release.image_pull_secret }}
{% endif %}
  maxModels: {{ release.max_models | default(100) }}
  registry: {{ release.registry | default("ghcr.io") }}
  syncInterval: {{ release.sync_interval | default("1h") }}

