# Copyright © Advanced Micro Devices, Inc., or its affiliates.
# SPDX-License-Identifier: MIT
# Touch to trigger CI to rebuild and republish the EPYC base image.

base_image:
  base_registry_namespace: silogenai
  base_repository: aim-epyc-base
  base_tag: "0.12"
  registry_host: docker.io
